<?php
    $DeptCode = null;
    $arrStr = explode('/', $_SERVER['REQUEST_URI']);
    $rowsStr = count($arrStr);

    if ((!isset($arrStr[2]))||($arrStr[2]=='index')){
      $ClassMain = " current";
    } else {
      $ClassMain = null;
    }

    for($i=0;$i<=$rowsStr;$i++){
        if (@$arrStr[$i] == 'dept'){
            $DeptCode = $arrStr[$i+1];
            break;
        }
    }
    for($i=0;$i<=$rowsStr;$i++){
        if (@$arrStr[$i] == 'column'){
            $ColumnCode = $arrStr[$i+1];
            break;
        }
    }

    $ClassBanner = null; $ClassWrite = null; $ClassList = null; $ClassManager = null;
      $ClassWriteArticle = null;
      $ClassListrdxw = null; $ClassListbbfc = null; $ClassListhdkj = null;
      $ClassListczzl = null; $ClassListcysh = null; $ClassListcgxy = null;
      $ClassManagerUser = null; $ClassStatistics = null;
      $NeedUEditor = 0; $NeedDatePicker = 0;
      $ShowAddUser = 0; $ShowModifyPwd  = 0;
      $NeedImageEditor = 0;
      $ShowPeriodListArticle = 0; $ShowPeriodStatistics = 0;
    if (isset($arrStr[2])) {
      switch ($arrStr[2]) {
        case 'writearticle': $ClassWrite   = " current"; $ClassWriteArticle = " class=\"current\"";
                             $NeedUEditor  = 1; $NeedDatePicker = 1; break;
        case  'imageupload': $ClassWrite = " current"; $ClassImageUpload = " class=\"current\"";
                             $NeedImageEditor = 1; break;
        case  'editarticle': $ClassWrite   = " current"; $ClassWriteArticle = " class=\"current\"";
                             $NeedUEditor  = 1; $NeedDatePicker = 1; break;
        case  'listarticle': $ClassList    = " current"; $ShowPeriodListArticle = 1;break;
        case  'usermanager': $ClassManager = " current"; $ClassManagerUser = " class=\"current\"";
                             $ShowAddUser  = 1; $ShowModifyPwd = 1; break;
        case  'statistics' : $ClassManager = " current"; $ClassStatistics = " class=\"current\"";
                             $ShowPeriodStatistics   = 1; break;
        case  'modifypwd'  : $ClassManager = " current"; break;
        default: break;
      }
    }
    if (isset($ColumnCode)) {
      switch ($ColumnCode) {
        case '1': $ClassListxw = " class=\"current\""; break;
        case '2': $ClassListxy = " class=\"current\""; break;
        case '3': $ClassListtx = " class=\"current\""; break;
        case '4': $ClassListxs = " class=\"current\""; break;
        case '5': $ClassListjy = " class=\"current\""; break;
        case '6': $ClassListqg = " class=\"current\""; break;
        case '7': $ClassListtz = " class=\"current\""; break;
        case '8': $ClassListky = " class=\"current\""; break;
        default: break;
      }
    }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>朋辈网后台管理系统</title>
<link rel="stylesheet" type="text/css" media="screen" href="/css/admin/reset.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/css/admin/style.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/css/admin/invalid.css" />
<?php if($NeedDatePicker) { ?>
<link rel="stylesheet" type="text/css" media="all" href="/css/admin/jquery-ui.css" />
<link rel="stylesheet" type="text/css" media="all" href="/css/admin/jquery-ui-timepicker-addon.css" />
<?php } ?>

<script type="text/javascript" src="/scripts/admin/jquery-1.10.1.min.js"></script>
<script type="text/javascript" src="/scripts/admin/simpla.jquery.configuration.js"></script>
<script type="text/javascript" src="/scripts/admin/facebox.js"></script>
<?php if($NeedUEditor) { ?>
<script type="text/javascript" src="/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/ueditor/ueditor.all.js"></script>
<?php } ?>

</head>
  <body><div id="body-wrapper"> <!-- Wrapper for the radial gradient background -->

    <div id="sidebar"><div id="sidebar-wrapper"> <!-- Sidebar with logo and menu -->

      <h1 id="sidebar-title"><a href="#">朋辈网后台管理系统</a></h1>

      <!-- Logo (221px wide) -->
      <a href="/admin"><img id="logo" src="/images/admin/logo.png" alt="logo" /></a>

      <!-- Sidebar Profile links -->
      <div id="profile-links">
        <a href="http://user.hfutonline.net/home" title="<?=$_SESSION['user']['UserName'];?>" target="_blank"><?=$_SESSION['user']['RealName'];?></a> | <?php
        if ($_SESSION['user']['Type'] == 1) echo "超级管理员";
        if ($_SESSION['user']['Type'] == 2) echo "网站审核";
        if ($_SESSION['user']['Type'] == 3) echo "网站编辑";
        ?><br />
        <?=$_SESSION['user']['DeptName'];?><br />
        <a href="/pengbei<?php if ($_SESSION['user']['DeptCode'] != "online") echo '/dept/id/'.$_SESSION['user']['DeptCode'];?>" title="返回前台" target="_blank">返回前台</a> | <a href="/login/logout" title="注销">注销</a>
      </div>        

      <ul id="main-nav">  <!-- Accordion Menu -->

        <li>
          <a href="/admin" class="nav-top-item no-submenu<?=$ClassMain?>">
            总体概览
          </a>
        </li>

<!--         <?php if ($_SESSION['user']['Type'] != 3) { ?>
          <li>
            <a href="#" class="nav-top-item">
              Banner
            </a>
            <ul>
              <li><a href="#">上传Banner</a></li>
              <li><a href="#">管理Banner</a></li>
            </ul>
          </li>
        <?php } ?> -->

        <?php if ($_SESSION['user']['Type'] == 1) { ?>
          <li> 
            <a href="#" class="nav-top-item<?=$ClassWrite?>">
              内容发布
            </a>
            <ul>
              <li><a href="/admin/writearticle"<?=$ClassWriteArticle?>>发表文章</a></li>
            </ul>
          </li>
        <?php } else { ?>
          <li> 
            <a href="/admin/writearticle" class="nav-top-item no-submenu<?=$ClassWrite?>">
              发表文章
            </a>
          </li>
        <?php } ?>

        <li>
          <a href="/admin/listarticle" class="nav-top-item no-submenu<?=$ClassList?>">
            <?php if ($_SESSION['user']['Type'] == 1) echo "内容管理"; else echo "文章管理"; ?>
          </a>
          <ul>
            <?php
                if(!empty($DeptCode)) $Dept = '/dept/'.$DeptCode;
                else $Dept = null;
            ?>
            <li><a href="/admin/listarticle<?=$Dept?>/column/1"<?=$ClassListxw?>>新闻</a></li>
            <li><a href="/admin/listarticle<?=$Dept?>/column/2"<?=$ClassListxy?>>学院</a></li>
            <li><a href="/admin/listarticle<?=$Dept?>/column/3"<?=$ClassListtx?>>团学</a></li>
            <li><a href="/admin/listarticle<?=$Dept?>/column/4"<?=$ClassListxs?>>活动</a></li>
            <li><a href="/admin/listarticle<?=$Dept?>/column/5"<?=$ClassListjy?>>学术</a></li>
            <li><a href="/admin/listarticle<?=$Dept?>/column/6"<?=$ClassListqg?>>就业</a></li>
            <li><a href="/admin/listarticle<?=$Dept?>/column/7"<?=$ClassListtz?>>考研</a></li>
            <li><a href="/admin/listarticle<?=$Dept?>/column/8"<?=$ClassListky?>>勤工</a></li>
          </ul>
        </li>

        <?php if ($_SESSION['user']['Type'] == 1) { ?>
        <li>
          <a href="#" class="nav-top-item<?=$ClassManager?>">
            网站管理
          </a>
          <ul>
            <li><a href="/admin/usermanager"<?=$ClassManagerUser?>>用户管理</a></li>
            <li><a href="/admin/statistics"<?=$ClassStatistics?>>发帖量管理</a></li>
          </ul>
        </li><?php } else { ?>
        <li>
          <a href="/admin/modifypwd" class="nav-top-item no-submenu<?=$ClassManager?>">
            修改密码
          </a>
        </li>
        <?php } ?>

      </ul> <!-- End #main-nav -->

    </div></div> <!-- End #sidebar -->

    <div id="main-content"> <!-- Main Content Section with everything -->

      <!-- Page Head -->
      <!-- <h2>朋辈网后台管理系统</h2> -->
      <!-- <p id="page-intro">What would you like to do?</p> -->

      <!-- Start Notifications -->

      <ul class="shortcut-buttons-set">

        <li><a class="shortcut-button" href="/admin"><span>
          <img src="/images/admin/icons/clock_48.png" alt="icon" /><br />
          待办事项
        </span></a></li>

<!--         <?php if ($_SESSION['user']['Type'] != 3) echo
        "<li><a class=\"shortcut-button\" href=\"#\"><span>
          <img src=\"/images/admin/icons/image_add_48.png\" alt=\"icon\" /><br />
          上传Banner
        </span></a></li>"; ?>

        <?php if ($_SESSION['user']['Type'] == 1) echo
        "<li><a class=\"shortcut-button\" href=\"#\"><span>
          <img src=\"/images/admin/icons/pencil_48.png\" alt=\"icon\" /><br />
          发布公告
        </span></a></li>"; ?>
 -->
        <li><a class="shortcut-button" href="/admin/writearticle"><span>
          <img src="/images/admin/icons/paper_content_pencil_48.png" alt="icon" /><br />
          发表文章
        </span></a></li>
        
        <?php if (($ShowPeriodListArticle)&&(($_SESSION['user']['Type'] != 3)&&($_SESSION['user']['DeptID'] == 0))) echo
        "<li><a class=\"shortcut-button\" href=\"/admin/periodstatistics/type/list\" rel=\"facebox\"><span>
          <img src=\"/images/admin/icons/period_48.png\" alt=\"icon\"/><br />
          自定义查看
        </span></a></li>"; ?>
        
        <?php if ($ShowAddUser) echo
        "<li><a class=\"shortcut-button\" href=\"/admin/userbox\" rel=\"facebox\"><span>
          <img src=\"/images/admin/icons/user_48.png\" alt=\"icon\"/><br />
          添加用户
        </span></a></li>"; ?>
        
        <?php if ($ShowModifyPwd) echo
        "<li><a class=\"shortcut-button\" href=\"/admin/modifypwd/type/facebox\" rel=\"facebox\"><span>
          <img src=\"/images/admin/icons/key_48.png\" alt=\"icon\"/><br />
          修改密码
        </span></a></li>"; ?>
        
        <?php if ($ShowPeriodStatistics) echo
        "<li><a class=\"shortcut-button\" href=\"/admin/periodstatistics\" rel=\"facebox\"><span>
          <img src=\"/images/admin/icons/period_48.png\" alt=\"icon\"/><br />
          自定义统计
        </span></a></li>"; ?>
        
      </ul><!-- End .shortcut-buttons-set -->

      <div class="clear"></div> <!-- End .clear -->
      
<!--        <div class="notification error png_bg">
        <div>
          你发表的<a href="#">n篇文章</a>未通过审核，修改后再次发表。
        </div>
      </div>

      <div class="notification attention png_bg">
        <a href="#" class="close"><img src="/images/admin/icons/cross_grey_small.png" title="关闭通知" alt="close" /></a>
        <div>
          你发表的<a href="#">n篇文章</a>不符合要求，但管理员<a href="#">admin</a>已协助修正。以后请避免错误。
        </div>
      </div>

      <div class="notification information png_bg">
        <a href="#" class="close"><img src="/images/admin/icons/cross_grey_small.png" title="关闭通知" alt="close" /></a>
        <a href="#" class="closeforever" title="不再提示">不再提示待审核信息</a>
        <div>
          你发表的<a href="#">n篇文章</a>处于待审核中，请耐心等待。
        </div>
      </div>

      <div class="notification success png_bg">
        <a href="#" class="close"><img src="/images/admin/icons/cross_grey_small.png" title="关闭通知" alt="close" /></a>
        <a href="#" class="closeforever" title="不再提示">不再提示通过信息</a>
        <div>
          你发表的<a href="#">n篇文章</a>已通过审核。
        </div>
      </div> -->

      <!-- End Notifications -->

      <div class="clear"></div>

      <?php echo $this->layout()->content; ?>

      <div class="clear"></div>


      <div id="footer">
        <small> <!-- Remove this notice or replace it with whatever you want -->
            CopyRight&#169;2013 合肥工业大学学工部(处)  大学生网络教育发展中心 | Powered by 朋辈网团队 | <a href="#">回到顶部</a>
        </small>
      </div><!-- End #footer -->
      
    </div> <!-- End #main-content -->
  </div></body>
</html>
