<?php
	$Title = null;

	if (!empty($this->arrArticle)) {
		$arrArticle = $this->arrArticle;
		$Title .= strRemoveBR($arrArticle[0]['Title'])." - ";
		$PageType = "article";
	} else {
		$PageType = $this->PageType;
	}

	if (!empty($this->arrColumn)) {
		$PageColumn = $this->arrPageColumn;
		$Title .= $PageColumn[0]['ColumnName']." - ";
	}

	if (!empty($this->arrDept)) {
		$arrDept = $this->arrDept;
		$Title .= $arrDept[0]['DeptID']?$arrDept[0]['DeptName']." - ":null;
		$DeptUrl = $arrDept[0]['DeptID']?"/dept/".$arrDept[0]['DeptCode']:null;
	} else {
		$DeptUrl = null;
	}
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="title" content="学子资讯网">
	<meta name="keywords" content="学子资讯网,朋辈网,朋辈,工大学子,合工大资讯,合肥工业大学资讯,合肥工业大学,合工大,大学生发展网络教育中心">
	<?php if ($Title==null) { ?>
	<meta name="description" content="合肥工业大学打造的心灵归属地、信息交流新平台。在这里我们一起谈梦想谈感受，关注朋友间的“小八卦”，亦不忘指点江山、激扬文字。这有感性的原创美文、思辨的华英评论。以同学的角度看新闻，以同龄人的身份引导舆论方向，以更为亲近的口吻传播正能量。">
	<?php } ?>
	<title><?=$Title?>工大学子 - 学子资讯网</title>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="stylesheet" type="text/css" href="http://book.hfutonline.net/css/reset.min.css">
	<link rel="stylesheet" type="text/css" href="/css/pengbei/basic.css">
	<?php if (($PageType=='index')||($PageType=='dept')) { ?>
	<?php } ?>
</head>
<body>
	<div id="header">
		<div id="nav">
			<a id="index" href="/pengbei">学子资讯网</a>
			<a class="xinzi" href="/pengbei/list/column/xw">新闻</a>
			<a class="xinzi" href="/pengbei/list/column/zx">资讯</a>
			<div class="img"></div>
		</div>
		<div id="loading">
			<img src="/images/pengbei/loading.gif">
			<br/>
			<p class="loading-char">学</p>
			<p class="loading-char">子</p>
			<p class="loading-char">资</p>
			<p class="loading-char">讯</p>
			<p class="loading-char">网</p>
		</div>
	</div>
	<div id="container">
		<div class="clearfloat"></div>

		<?php echo $this->layout()->content; ?>
		
		<div class="clearfloat"></div>
	</div>

	<div class="footer">
		<p>CopyRight©2006-2014 合肥工业大学党委学工部（处）大学生发展网络教育中心 All rights reserved.</p>
	</div>

</body>
</html>