<?php
	$arrArticle	= $this->arrArticle;

	$ID			= $arrArticle[0]['ID'];
	$Title		= $arrArticle[0]['Title'];
	$ColumnID	= $arrArticle[0]['ColumnID'] - 1;
	$DeptID		= $arrArticle[0]['DeptID'];
	$Article	= $arrArticle[0]['Article'];
	$Author		= $arrArticle[0]['Author'];
	$PublishTime= date('Y-m-d',$arrArticle[0]['PublishTime']);
	$Click		= $arrArticle[0]['FakeClick'] + $arrArticle[0]['RealClick'];
	$Click		+=isset($_SESSION['user']['Type'])?0:1;
	$TopAtDept	= $arrArticle[0]['TopAtDept'];
	$TopAtAll	= $arrArticle[0]['TopAtAll'];

	$arrDept	= $this->arrDept;
	$DeptName	= $arrDept[0]['DeptName'];
	$DeptCode	= $arrDept[0]['DeptCode'];
	$DeptUrl	= $DeptID?"/dept/id/".$arrDept[0]['DeptCode']:null;
	$DeptUrl4List= $DeptID?"/dept/".$arrDept[0]['DeptCode']:null;
	$arrColumn	= $this->arrColumn;
	$ColumnName	= $arrColumn[$ColumnID]['ColumnName'];
	$ColumnCode	= $arrColumn[$ColumnID]['ColumnCode'];

	// 计算中文字符串长度
	function utf8_strlen($string = null) {
		preg_match_all("/./us", $string, $match);
		return count($match[0]);
	}

	function strRemoveBR($str) {
		return preg_replace('/<br(\/)?(\s)*(\/)?>/i','',$str);
	}

	function utf8Substr($str, $from, $len) {
		$str = strRemoveBR($str);
		if (utf8_strlen($str)>$len-$from) {
			$str = preg_replace('#^(?:[\x00-\x7F]|[\xC0-\xFF][\x80-\xBF]+){0,'.$from.'}'.
					'((?:[\x00-\x7F]|[\xC0-\xFF][\x80-\xBF]+){0,'.$len.'}).*#s','$1',$str);
			$str.= "...";
		}
		return $str;
	}

	function maxlist($arrLength) {
		$ListLength = 4;
		return ($ListLength>$arrLength)?$arrLength:$ListLength;
	}
?>

<link rel="stylesheet" type="text/css" href="/css/pengbei/article.css">

<div class="main">
    <ul>
        <li class="rung"></li>
        <li id="bread">
            <div>
                <a href="/pengbei">首页</a><span>&nbsp;&gt;&gt;&nbsp;</span><a href="/pengbei/list/column/<?=$ColumnCode?>"><?=$ColumnName?></a><span>&nbsp;&gt;&gt;&nbsp;</span><a>正文</a>
            </div>
        </li>
        <li class="rung"></li>
    </ul>
    <div id="article">
        <h1 class="green"><?=$Title?></h1>
        <span><?=$Author?>&nbsp;|&nbsp;<?=$PublishTime?>&nbsp;|&nbsp;<span class="green"><?=$Click?></span>views</span>
        <div class="hr"></div>
        <div>
            <?=$Article?>
        </div>
    </div>
</div>