<?php
	$arrDept	= $this->arrDept;
	$DeptName	= $arrDept[0]['DeptName'];
	$DeptCode	= $arrDept[0]['DeptCode'];
	$DeptUrl	= $arrDept[0]['DeptID']?"/dept/id/".$arrDept[0]['DeptCode']:null;

	$arrListrdxw = $this->arrListrdxw;
	$arrListbbfc = $this->arrListbbfc;
	$arrListhdkj = $this->arrListhdkj;
	$arrListczzl = $this->arrListczzl;
	$arrListcysh = $this->arrListcysh;
	$arrListcgxy = $this->arrListcgxy;

	// 计算中文字符串长度
	function utf8_strlen($string = null) {
		preg_match_all("/./us", $string, $match);
		return count($match[0]);
	}

	function strRemoveBR($str) {
		return preg_replace('/<br(\/)?(\s)*(\/)?>/i','',$str);
	}

	function utf8Substr($str, $from, $len) {
		$str = strRemoveBR($str);
		if (utf8_strlen($str)>$len-$from) {
			$str = preg_replace('#^(?:[\x00-\x7F]|[\xC0-\xFF][\x80-\xBF]+){0,'.$from.'}'.
					'((?:[\x00-\x7F]|[\xC0-\xFF][\x80-\xBF]+){0,'.$len.'}).*#s','$1',$str);
			$str.= "...";
		}
		return $str;
	}

	function maxlist($arrLength) {
		$ListLength = 4;
		return ($ListLength>$arrLength)?$arrLength:$ListLength;
	}
?>

<link rel="stylesheet" type="text/css" href="/css/pengbei/index.css">
<style>
	#loading{display: none;}
    .rung{position:absolute;top:95px;width:100%;height:16px;background-color:#2eb0ad;}
    .rung2{top:123px;}
    #college{background:#2a9b99;width:300px;height:70px;position:absolute;top:82px;left:50%;margin-left:-150px;text-align:center;}
    #college p{font-size:24px;line-height:68px;}
    #header{height:70px;}
    #nav,.background{opacity:1;filter:alpha(opacity=100);}
    .background{margin-left:-50%;}
    .header-phone{margin-left:-435px;}
</style>

<div id="content">
	<div class="rung"></div>
	<div class="rung rung2"></div>
	<div id="college">
		<p><?=$DeptName?></p>
	</div>
    <ul id="ul">
        <li class="xinwen list">
            <div>
                <ul class="left-list">
                    <h1 class="list-h1">新闻</h1>
                    <li class="active"><a class="left-list-link">校内</a></li>
                    <li><a class="left-list-link">学院</a></li>
                    <li><a class="left-list-link">团学</a></li>
                </ul>
                <ul class="title-list">
                </ul>
            </div>
        </li>
        <li class="zixun list">
            <div>
                <ul class="left-list">
                    <h1 class="list-h1">通知</h1>
                    <li class="active"><a class="left-list-link">活动</a></li>
                    <li><a class="left-list-link">学术</a></li>
                    <li><a class="left-list-link">就业</a></li>
                    <li><a class="left-list-link">考研</a></li>
                    <li><a class="left-list-link">勤工</a></li>
                </ul>
                <ul class="title-list">
                </ul>
            </div>
        </li>
        <li id="phone">
            <div id="new-content">
                <ul id="top">
                <!-- <li><a href="#"><img src="/images/pengbei/banner/5.jpg"></a></li> -->
                </ul>
                <div id="prev"></div>
                <div id="next"></div>
                <a class="top-link" href="#" target="_blank">
                    <p id="link"></p>
                    <span id="count"></span>
                </a>
            </div>
        </li>
    </ul>
    <div class="background background-1"></div>
    <div class="background background-2"></div>
    <div class="background background-3"></div>
</div>

<div id="footer-link">
	<ul>
        <li><a href="/pengbei/dept/id/som">管理学院</a></li>
        <li><a href="/pengbei/dept/id/wgy">外国语学院</a></li>
        <li><a href="/pengbei/dept/id/mks">马克思主义学院</a></li>
        <li><a href="/pengbei/dept/id/ci">计算机与信息学院</a></li>
        <li><a href="/pengbei/dept/id/mse">材料科学与工程学院</a></li>
        <li><a href="/pengbei/dept/id/sbfe">生物与食品工程学院</a></li>
        <li><a href="/pengbei/dept/id/jj">经济学院</a></li>
        <li><a href="/pengbei/dept/id/yxgc">医学工程学院</a></li>
        <li><a href="/pengbei/dept/id/jy">建筑与艺术学院</a></li>
        <li><a href="/pengbei/dept/id/ea">电气与自动化学院</a></li>
        <li><a href="/pengbei/dept/id/civil">土木与水利工程学院</a></li>
        <li><a href="/pengbei/dept/id/dw">电子科学与应用物理学院</a></li>
        <li><a href="/pengbei/dept/id/sx">数学学院</a></li>
        <li><a href="/pengbei/dept/id/hg">化学与化工学院</a></li>
        <li><a href="/pengbei/dept/id/jt">交通运输工程学院</a></li>
        <li><a href="/pengbei/dept/id/geos">资源与环境工程学院</a></li>
        <li><a href="/pengbei/dept/id/jq">机械与汽车工程学院</a></li>
        <li><a href="/pengbei/dept/id/yqkx">仪器科学与光电工程学院</a></li>
        <li><a href="/pengbei/dept/id/rj">软件学院</a></li>
	</ul>
</div>

<script src="http://libs.baidu.com/jquery/1.8.3/jquery.min.js"></script>
<script src="/scripts/pengbei/college.js"></script>