<link rel="stylesheet" type="text/css" href="/css/pengbei/index.css">

<div id="content">
    <ul id="ul">
        <li class="xinwen list">
            <div>
                <ul class="left-list">
                    <h1 class="list-h1">新闻</h1>
                    <li class="active"><a class="left-list-link">校内</a></li>
                    <li><a class="left-list-link">学院</a></li>
                    <li><a class="left-list-link">团学</a></li>
                </ul>
                <ul class="title-list">
                </ul>
            </div>
        </li>
        <li class="zixun list">
            <div>
                <ul class="left-list">
                    <h1 class="list-h1">通知</h1>
                    <li class="active"><a class="left-list-link">活动</a></li>
                    <li><a class="left-list-link">学术</a></li>
                    <li><a class="left-list-link">就业</a></li>
                    <li><a class="left-list-link">考研</a></li>
                    <li><a class="left-list-link">勤工</a></li>
                </ul>
                <ul class="title-list">
                </ul>
            </div>
        </li>
    </ul>
    <div class="background header-phone">
    	<div id="new-content">
            <ul id="top">
<!--                 <li><a href="#"><img src="/images/pengbei/banner/3.jpg"></a></li>
                <li><a href="#"><img src="/images/pengbei/banner/1.jpg"></a></li>
                <li><a href="#"><img src="/images/pengbei/banner/2.jpg"></a></li>
                <li><a href="#"><img src="/images/pengbei/banner/4.jpg"></a></li>
                <li><a href="#"><img src="/images/pengbei/banner/6.jpg"></a></li>
                <li><a href="#"><img src="/images/pengbei/banner/5.jpg"></a></li> -->
            </ul>
            <div id="prev"></div>
            <div id="next"></div>
            <a class="top-link" href="#" target="_blank">
                <p id="link"></p>
                <span id="count"></span>
            </a>
    	</div>
    </div>
    <div class="background background-1"></div>
    <div class="background background-2"></div>
    <div class="background background-3"></div>
    <img id="full" title="全景" src="/images/pengbei/full.png">
</div>

<div id="footer-link">
	<ul>
		<li><a href="/pengbei/dept/id/som">管理学院</a></li>
		<li><a href="/pengbei/dept/id/wgy">外国语学院</a></li>
		<li><a href="/pengbei/dept/id/mks">马克思主义学院</a></li>
		<li><a href="/pengbei/dept/id/ci">计算机与信息学院</a></li>
        <li><a href="/pengbei/dept/id/mse">材料科学与工程学院</a></li>
        <li><a href="/pengbei/dept/id/sbfe">生物与食品工程学院</a></li>
		<li><a href="/pengbei/dept/id/jj">经济学院</a></li>
		<li><a href="/pengbei/dept/id/yxgc">医学工程学院</a></li>
		<li><a href="/pengbei/dept/id/jy">建筑与艺术学院</a></li>
		<li><a href="/pengbei/dept/id/ea">电气与自动化学院</a></li>
        <li><a href="/pengbei/dept/id/civil">土木与水利工程学院</a></li>
        <li><a href="/pengbei/dept/id/dw">电子科学与应用物理学院</a></li>
		<li><a href="/pengbei/dept/id/sx">数学学院</a></li>
		<li><a href="/pengbei/dept/id/hg">化学工程学院</a></li>
		<li><a href="/pengbei/dept/id/jt">交通运输工程学院</a></li>
		<li><a href="/pengbei/dept/id/geos">资源与环境工程学院</a></li>
		<li><a href="/pengbei/dept/id/jq">机械与汽车工程学院</a></li>
        <li><a href="/pengbei/dept/id/yqkx">仪器科学与光电工程学院</a></li>
		<li><a href="/pengbei/dept/id/rj">软件学院</a></li>
	</ul>
</div>


<script src="http://libs.baidu.com/jquery/1.8.3/jquery.min.js"></script>
<script src="/scripts/pengbei/index.js"></script>