<?php
	$DeptUrl4List = null;
	if (!empty($this->arrDept)) {
		$arrDept		= $this->arrDept;
		$DeptName		= $arrDept[0]['DeptName'];
		$DeptCode		= $arrDept[0]['DeptCode'];
		$DeptUrl		= $arrDept[0]['DeptID']?"/dept/id/".$arrDept[0]['DeptCode']:null;
		$DeptUrl4List	= $arrDept[0]['DeptID']?"/dept/".$arrDept[0]['DeptCode']:null;
	}

	$PageColumn	= $this->arrPageColumn;
	$ColumnID	= $PageColumn[0]['ColumnID'] - 1;
	$ColumnName	= $PageColumn[0]['ColumnName'];
	$ColumnCode	= $PageColumn[0]['ColumnCode'];

	$arrColumn	= $this->arrColumn;

	global $arrList;
	switch ($ColumnCode) {
		case 'rdxw': $arrList = $this->arrListrdxw; break;
		case 'bbfc': $arrList = $this->arrListbbfc; break;
		case 'hdkj': $arrList = $this->arrListhdkj; break;
		case 'czzl': $arrList = $this->arrListczzl; break;
		case 'cysh': $arrList = $this->arrListcysh; break;
		case 'cgxy': $arrList = $this->arrListcgxy; break;
		// default : $arrList = $this->arrListrdxw; break;
	}
	$paginator = $this->paginator;

	//截取文章
	function cutstr_html($string, $sublen)
	{
		$string = strip_tags($string);
		$string = preg_replace ('/\n/is', '', $string);
		$string = preg_replace ('/ |　/is', '', $string);
		$string = preg_replace ('/&nbsp;/is', '', $string);

		preg_match_all("/[\x01-\x7f]|[\xc2-\xdf][\x80-\xbf]|\xe0[\xa0-\xbf][\x80-\xbf]|[\xe1-\xef][\x80-\xbf][80-\xbf]|\xf0[\x90-\xbf][\x80-\xbf][\x80-\xbf]|[\xf1-\xf7][\x80-\xbf][\x80-\xbf][\x80-\xbf]/", $string, $t_string);
		if(count($t_string[0]) - 0 > $sublen) $string = join('', array_slice($t_string[0], 0, $sublen))."";
		else $string = join('', array_slice($t_string[0], 0, $sublen));
		
		return $string;
	}

	// 计算中文字符串长度
	function utf8_strlen($string = null) {
		preg_match_all("/./us", $string, $match);
		return count($match[0]);
	}

	function strRemoveBR($str) {
		return preg_replace('/<br(\/)?(\s)*(\/)?>/i','',$str);
	}

	function utf8Substr($str, $from, $len) {
		$str = strRemoveBR($str);
		if (utf8_strlen($str)>$len-$from) {
			$str = preg_replace('#^(?:[\x00-\x7F]|[\xC0-\xFF][\x80-\xBF]+){0,'.$from.'}'.
					'((?:[\x00-\x7F]|[\xC0-\xFF][\x80-\xBF]+){0,'.$len.'}).*#s','$1',$str);
			$str.= "...";
		}
		return $str;
	}

	function maxlist($arrLength) {
		$ListLength = 4;
		return ($ListLength>$arrLength)?$arrLength:$ListLength;
	}
?>

<div id="main">
	<?php
		if (!empty($this->arrDept)) {?>
		<a href="/pengbei<?=$DeptUrl?>" title="<?=$DeptName?>">
			<div class="xueyuan-title">
				<span><?=$DeptName?></span>
			</div>
		</a>
	<?php } ?>

	<div class="clearfloat"></div>
	<div class="main-rightMain">
	
	<!--模块2:列表模块-->
	<div class="pengbei-list">

		<div class="list-left">
		
			<div class="crumbs" id="<?=$ColumnCode?>">
				<h1><a href="/pengbei">首页</a> > <a href="/pengbei/list/column/<?=$ColumnCode?>"><?=$ColumnName?></a></h1>
			</div>

			<?php
				$row=count($paginator);
				if($row){
					foreach ($paginator as $value) {
						$ID			= $value['ID'];
						$Title		= $value['Title'];
						$Article	= cutstr_html($value['Article'], 100);
						$Author		= $value['Author'];
						$PublishTime= date('Y-m-d',$value['PublishTime']);
						$Click		= $value['FakeClick'] + $value['RealClick'];
						$TopAtDept	= $value['TopAtDept'];
						$TopAtAll	= $value['TopAtAll'];
						{ ?>
							<ul><li>
								<div class="fir-title">
									<div class="content <?=$ColumnCode?>">
										<p class="content-title">
											<a href="/pengbei/article/id/<?=$ID?>" class="listtitle" target="_blank"><?=$Title?></a>
										</p>
										<p class="content_source">
											<span><a style="color: blue;"><?=$Author?></a></span>
											<span>|</span>
											<span><?=$PublishTime?></span>
											<span>|</span>
											<span><?=$Click?></span>
											<span>views</span>
										</p>
									</div>
									<span class="content-comment"><?=$Click?></span>
								</div>
								<div class="article">
									<span class="words">　　<?=$Article?>……</span><span><a href="/pengbei/article/id/<?=$ID?>" target="_blank">阅读全文»</a></span>
								</div>
							</li></ul>
						<?php }
					}
				}
			?>
		</div>

		<div id="list-fenye">
			<?php echo $this->paginationControl($this->paginator_all,'Elastic','pengbei/pagination_control.phtml'); ?>
		</div>

		<div class="list-right">
			<?php
				for ($i=0; $i <= 5; $i++) { 
					if($i!=$ColumnID) {
						{ ?>
						<div class="list-lanmu">
							<div class="list-title <?=$arrColumn[$i]['ColumnCode']?>">
								<h2><a href="/pengbei/list<?=$DeptUrl4List?>/column/<?=$arrColumn[$i]['ColumnCode']?>"><?=$arrColumn[$i]['ColumnName']?></a></h2>
							</div>
							<ul>
						<?php }
						switch ($i) {
							case '0': $arrList = $this->arrListrdxw; break;
							case '1': $arrList = $this->arrListbbfc; break;
							case '2': $arrList = $this->arrListhdkj; break;
							case '3': $arrList = $this->arrListczzl; break;
							case '4': $arrList = $this->arrListcysh; break;
							case '5': $arrList = $this->arrListcgxy; break;
							// default : $arrList = $this->arrListrdxw; break;
						}
						$liNum = maxlist(count($arrList) - 1);
						for ($j=0; $j <= $liNum; $j++) { ?>
							<li><span><a href="/pengbei/article/id/<?=$arrList[$j]['ID']?>" title="<?=strRemoveBR($arrList[$j]['Title'])?>" target="_blank"><?=utf8Substr($arrList[$j]['Title'], 0, 21)?></a></span></li>
						<?php }
						{ ?>
							</ul>
							</div>
						<?php }
					} else {
						continue;
					}
				}
			?>
		</div>
			
	</div>
	<!--/模块2结束-->

	<div class="clearfloat"></div>

	</div>

</div>