<div class="content-box">
    <div class="content-box-header">
        <h3 style="cursor: s-resize;">上传图片</h3>
    </div>
    <div class="content-box-content">
    	<div class="upload-btn-box">
            <form enctype="multipart/form-data" id="imageForm" action="/admin/imageupload/method/post" method="post">
                <input id="uploadinput" name="imageFile" type="file" onchange="updateImage(this)" accept="image/*" />
                <?php if (($_SESSION['user']['Type'] == 1)||($_SESSION['user']['DeptID'] == 0)) { 
                    echo"<p>选择学院：<br><select id=\"image-deptid\" name=\"deptid\" class=\"dept\"><option value=\"-1\" selected=\"selected\"></   option>";
                    $arrDept = $this->arrDept;
                    $rowsDept = count($arrDept);
                    for($i=0;$i<$rowsDept;$i++) {
                        if ($arrDept[$i]['DeptID'] == 0) echo "<option value=\"".$arrDept[$i]['DeptID']."\">首页</option>";
                        else echo "<option value=\"".$arrDept[$i]['DeptID']."\">".$arrDept[$i]['DeptName']."</option>";
                    }
                    echo "</select></p>"; 
                } 
                ?>
            </form>
    		<p><a class="btn" onclick="uploadClick()">选择图片</a></p>
            
			<p><a class="btn" onclick="uploadCheck()">上传图片</a><a class="btn" onclick="uploadCancel()">取消</a></p>
    	</div>
    	
		
		<div id="preview">
		    <img id="imghead" width="480" height="280" border="0" src='/images/admin/upload-mornal.jpg'><!--无预览时的默认图像，自己弄一个-->
		</div>
		<div class="clear"></div>
		<script type="text/javascript" src="/scripts/admin/imageuploadplugin.js"></script>
    </div>
</div>
<div class="content-box">
	<div class="content-box-header">
        <h3 style="cursor: s-resize;">图片管理</h3>
    </div>
    <div class="content-box-content">
        <div class="tab-content default-tab">
            <table>
                <thead>
                    <tr>
                        <th>图片名称</th>
                        <th>学院</th>
                        <th>发布者</th>
                        <th>发布时间</th>
                        <th>图片操作</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                foreach ($this->imageArr as $key => $value){
                    ?>
                    <tr>
                        <th><?php echo $value['image_name'];?></th>
                        <th><?php //院系名称
                                $DeptMapper = new Application_Model_DepartmentMapper();
                                $arrDept = $DeptMapper->findDept($value['dept_id']);
                                if(!empty($arrDept)) echo $arrDept[0]['DeptName'];?></th>
                        <th><?php echo $value['image_owner'];?></th>
                        <th><?php echo date('Y-m-d H:i:s',$value['image_date']);?></th>
                        <th><a onclick="imageDel('<?php echo $value['image_name']?>','<?php echo date('/Y/m/',$value['image_date'])?>')">删除</a></th>
                    </tr>
                    <?php
                    }
                    ?>
                </tbody>
            </table>
        
        
        </div>
    </div>
</div>