<?php
	function ListArticle($row,$paginator)
	{
		$row=count($paginator);
		if($row){
			foreach ($paginator as $value) {
				$ID=$value['ID'];
				$Title=$value['Title'];
				$Column=$value['ColumnID'];
				$DeptID=$value['DeptID'];
				$WriteTime=date('Y-m-d',$value['WriteTime']);
				$WriterID=$value['WriterID'];
				$Published=$value['Published'];
				$TopAtDept=$value['TopAtDept'];
				$TopAtAll=$value['TopAtAll'];
				$RejectReason=$value['RejectReason'];

				//栏目名称
				$ColumnMapper = new Application_Model_ColumnMapper();
				$arrColumn = $ColumnMapper->findColumn($Column);
				if(!empty($arrColumn)) $Column = $arrColumn[0]['ColumnName'];

				//院系名称
				$DeptMapper = new Application_Model_DepartmentMapper();
				$arrDept = $DeptMapper->findDept($DeptID);
				if(!empty($arrDept)) $Dept = $arrDept[0]['DeptName'];

				//用户名称
				$UserMapper = new Application_Model_UserMapper();
				$arrUser = $UserMapper->findUserByID($WriterID);
				if(!empty($arrUser)) {
					$WriterName = $arrUser[0]['UserName'];
					$WriterRealName = $arrUser[0]['RealName'];
					$Writer = "<span title=\"$WriterName\">$WriterRealName</span>";
				}
				//判断是否为自己发表的文章
				if ($WriterID == $_SESSION['user']['UserID'])
					$WriterIsSelf = 1;
				else
					$WriterIsSelf = 0;

				//审核状态 及 置顶状态
				if ($_SESSION['user']['Type'] != 3){
					switch ($Published){
						case -1: $PublishInfo="<span style=\"color:orange;\">已退稿</span>";break;
						case  0: $PublishInfo="<span style=\"color:red;\">待审核</span>";break;
						case  1: $PublishInfo="已审核";break;
						case  2: $PublishInfo="已修正";break;
					}
				} else {
					switch ($Published){
						case -1: $PublishInfo="<span style=\"color:red;\">已退稿</span>";break;
						case  0: $PublishInfo="<span style=\"color:mediumblue;\">待审核</span>";break;
						case  1: $PublishInfo="已审核";break;
						case  2: $PublishInfo="已修正";break;
					}
				}
				if ($_SESSION['user']['Type'] == 1){
					if($TopAtAll==1) $PublishInfo .="<span title=\"首页置顶\">[首]</span>";
					if($TopAtDept==1) $PublishInfo .="<span title=\"院系置顶\">[院]</span>";
				} else {
					if ($_SESSION['user']['DeptID'] == 0){
						if($TopAtAll==1) $PublishInfo .="<span title=\"首页置顶\">[首]</span>";
						if($TopAtDept==1) $PublishInfo .="<span title=\"院系置顶\">[院]</span>";
					} else {
						if($TopAtDept==1) $PublishInfo .="<span title=\"院系置顶\">[顶]</span>";
					}
				}
			
				echo "
				<tr>";
				if ($_SESSION['user']['Type'] == 1) echo "
					<td><input type=\"checkbox\" value=\"$ID\" /></td>";
				echo "
					<td><a href=\"/pengbei/article/id/$ID\" title=\"预览文章\" target=\"_blank\">$Title</a></td>
					<td>$Column</td>";
				if (($_SESSION['user']['Type'] == 1)||(($_SESSION['user']['Type'] == 2)&&($_SESSION['user']['DeptID'] == 0))) echo "
					<td>$Dept</td>";
				echo "
					<td>$WriteTime</td>
					<td>$Writer</td>
					<td>$PublishInfo</td>
					<td>
					<!-- Icons -->";

				if ($_SESSION['user']['Type'] != 3) {
					if ($WriterIsSelf) echo "
						<a href=\"/admin/editarticle/id/".$ID."\" title=\"编辑\"><img src=\"/images/admin/icons/pencil.png\" alt=\"编辑\" /></a>";
					else echo "
						<a href=\"/admin/editarticle/id/".$ID."\" title=\"修正\"><img src=\"/images/admin/icons/hammer_screwdriver.png\" alt=\"修正\" /></a>";
					if ($Published == 0) echo "
						<a href=\"/admin/checkarticle/id/".$ID."\" title=\"审核\"><img src=\"/images/admin/icons/check.png\" alt=\"审核\" /></a>";
						else {
							if ($Published == -1) echo "
								<a title=\"发帖人修改后才可审核\"><img src=\"/images/admin/icons/blank.png\" /></a>";
							else echo " <img src=\"/images/admin/icons/blank.png\" />";
						}
					echo "
						<a href=\"/admin/rejectarticle/id/".$ID."\" title=\"退稿\" rel=\"facebox\"><img src=\"/images/admin/icons/reject.png\" alt=\"退稿\" /></a>
						<a href=\"/admin/deletearticle/id/".$ID."\" title=\"删除\" class=\"delete\"><img src=\"/images/admin/icons/cross.png\" alt=\"删除\" /></a>";
				} else {
					if ($Published == 0) echo "
						<a href=\"/admin/editarticle/id/".$ID."\" title=\"编辑\"><img src=\"/images/admin/icons/pencil.png\" alt=\"编辑\" /></a>
						<a href=\"/admin/deletearticle/id/".$ID."\" title=\"删除\" class=\"delete\"><img src=\"/images/admin/icons/cross.png\" alt=\"删除\" /></a>";
					if ($Published == -1) echo "
						<a href=\"/admin/editarticle/id/".$ID."\" title=\"修正\"><img src=\"/images/admin/icons/hammer_screwdriver.png\" alt=\"修正\" /></a>
						<a href=\"/admin/deletearticle/id/".$ID."\" title=\"删除\" class=\"delete\"><img src=\"/images/admin/icons/cross.png\" alt=\"删除\" /></a>";
				}

				echo "
					</td>
				</tr>";

			}

		}
	}
?>
<?php if (($_SESSION['user']['DeptID'] == 0)&&($_SESSION['user']['Type'] != 3)){?>
<div class="content-box closed-box">

	<div class="content-box-header">
		<h3>选择院系进行查看　　　　　　　　　　　　　　　　　　　　　　　　　</h3>
	</div> <!-- End .content-box-header -->

	<div class="content-box-content">

		<div class="tab-content default-tab">

			<?php
				$DeptCodeSelected = $this->DeptCodeSelected;
				$arrAllDept = $this->arrAllDept;
				$rowsAllDept = count($arrAllDept);
				$Selected = "notselected";
				if (empty($DeptCodeSelected)) $Selected = "selected";
				echo "<a href=\"/admin/listarticle\" class=\"".$Selected."\">全部学院文章</a></br>";
				for($i=0;$i<$rowsAllDept;$i++){
					if ($DeptCodeSelected == $arrAllDept[$i]['DeptCode'])
						$Selected = "selected";
					else
						$Selected = "notselected";
					echo "<a href=\"/admin/listarticle/dept/".$arrAllDept[$i]['DeptCode']."\" class=\"".$Selected."\">".$arrAllDept[$i]['DeptName']."</a>";
					$BlankLength = 13 - mb_strlen($arrAllDept[$i]['DeptName'],"UTF8");
					for ($b=1;$b<$BlankLength;$b++)
						echo "　";
					if (($i+1)%4==0) echo "</br>";
				}
			?>

		</div>

	</div> <!-- End .content-box-content -->

</div> <!-- End .content-box -->
<?php }?>







<div class="content-box"><!-- Start Content Box -->

	<div class="content-box-header">

		<h3><?=$this->ListTitle;?></h3>

		<ul class="content-box-tabs">
			<li><a href="#all" title="所有文章" id="alltab" class="default-tab">所有文章</a></li>
			<li><a href="#wait" title="待审核的文章" id="waittab">待审核</a></li>
			<li><a href="#reject" title="已退稿的文章" id="rejecttab">已退稿</a></li>
			<li><a href="#publish" title="已审核或修正的文章" id="publishtab">已审核</a></li>
		</ul>

		<div class="clear"></div>

	</div> <!-- End .content-box-header -->

	<div class="content-box-content">

		<!-- 全部文章 -->
		<div class="tab-content default-tab" id="all">

			<table>

			<thead>

				<tr>
					<?php
						if ($_SESSION['user']['Type'] == 1)
							echo "<th><input class=\"check-all\" type=\"checkbox\" /></th>";
					?>
					<th>文章标题</th>
					<th>所属栏目</th>
					<?php
						if (($_SESSION['user']['Type'] == 1)||(($_SESSION['user']['Type'] == 2)&&($_SESSION['user']['DeptID'] == 0))) echo "<th>所属学院</th>";
					?>
					<th>发帖时间</th>
					<th>发帖人</th>
					<th>状态</th>
					<th>文章操作</th>
				</tr>

			</thead>

			<tbody>

				<?php
					global $row_all;
					$paginator_all=$this->paginator_all;
					ListArticle($row_all,$paginator_all);
				?>
			
			</tbody>

			<tfoot>
				<tr>
					<td colspan="6">
						<div class="bulk-actions align-left">
							<?php
								if ($_SESSION['user']['Type'] == 1) echo"
								<input type=\"submit\" class=\"button\" value=\"删除\">";
							?>
						</div>

						<div class="pagination">
							<?php echo $this->paginationControl($this->paginator_all,
								'Elastic',//页码样式 
								'admin/pagination_control.phtml'//页码模板
								);
							?>
						</div> <!-- End .pagination -->
						<div class="clear"></div>
					</td>
				</tr>
			</tfoot>

			</table>

		</div> <!-- End #all -->



		<!-- 待审核的文章 -->
		<div class="tab-content" id="wait">

			<table>

			<thead>

				<tr>
					<?php
						if ($_SESSION['user']['Type'] == 1)
							echo "<th><input class=\"check-all\" type=\"checkbox\" /></th>";
					?>
					<th>文章标题</th>
					<th>所属栏目</th>
					<?php
						if (($_SESSION['user']['Type'] == 1)||(($_SESSION['user']['Type'] == 2)&&($_SESSION['user']['DeptID'] == 0))) echo "<th>所属学院</th>";
					?>
					<th>发帖时间</th>
					<th>发帖人</th>
					<th>状态</th>
					<th>文章操作</th>
				</tr>

			</thead>

			<tbody>

				<?php
					global $row_wait;
					$paginator_wait=$this->paginator_wait;
					ListArticle($row_wait,$paginator_wait);
				?>
			
			</tbody>

			<tfoot>
				<tr>
					<td colspan="6">
						<div class="bulk-actions align-left">
							<?php
								if ($_SESSION['user']['Type'] == 1) echo"
								<input type=\"submit\" class=\"button\" value=\"删除\">";
							?>
						</div>

						<div class="pagination">
							<?php echo $this->paginationControl($this->paginator_wait,
								'Elastic',//页码样式 
								'admin/pagination_control.phtml'//页码模板
								);
							?>
						</div> <!-- End .pagination -->
						<div class="clear"></div>
					</td>
				</tr>
			</tfoot>

			</table>

		</div> <!-- End #wait -->



		<!-- 已退稿的文章 -->
		<div class="tab-content" id="reject">

			<table>

			<thead>

				<tr>
					<?php
						if ($_SESSION['user']['Type'] == 1)
							echo "<th><input class=\"check-all\" type=\"checkbox\" /></th>";
					?>
					<th>文章标题</th>
					<th>所属栏目</th>
					<?php
						if (($_SESSION['user']['Type'] == 1)||(($_SESSION['user']['Type'] == 2)&&($_SESSION['user']['DeptID'] == 0))) echo "<th>所属学院</th>";
					?>
					<th>发帖时间</th>
					<th>发帖人</th>
					<th>状态</th>
					<th>文章操作</th>
				</tr>

			</thead>

			<tbody>

				<?php
					global $row_reject;
					$paginator_reject=$this->paginator_reject;
					ListArticle($row_reject,$paginator_reject);
				?>
			
			</tbody>

			<tfoot>
				<tr>
					<td colspan="6">
						<div class="bulk-actions align-left">
							<?php
								if ($_SESSION['user']['Type'] == 1) echo"
								<input type=\"submit\" class=\"button\" value=\"删除\">";
							?>
						</div>

						<div class="pagination">
							<?php echo $this->paginationControl($this->paginator_reject,
								'Elastic',//页码样式 
								'admin/pagination_control.phtml'//页码模板
								);
							?>
						</div> <!-- End .pagination -->
						<div class="clear"></div>
					</td>
				</tr>
			</tfoot>

			</table>

		</div> <!-- End #reject -->



		<!-- 已审核或修正的文章 -->
		<div class="tab-content" id="publish">

			<table>

			<thead>

				<tr>
					<?php
						if ($_SESSION['user']['Type'] == 1)
							echo "<th><input class=\"check-all\" type=\"checkbox\" /></th>";
					?>
					<th>文章标题</th>
					<th>所属栏目</th>
					<?php
						if (($_SESSION['user']['Type'] == 1)||(($_SESSION['user']['Type'] == 2)&&($_SESSION['user']['DeptID'] == 0))) echo "<th>所属学院</th>";
					?>
					<th>发帖时间</th>
					<th>发帖人</th>
					<th>状态</th>
					<?php
						if ($_SESSION['user']['Type'] == 3);
						else echo "<th>文章操作</th>";
					?>
				</tr>

			</thead>

			<tbody>

				<?php
					global $row_publish;
					$paginator_publish=$this->paginator_publish;
					ListArticle($row_publish,$paginator_publish);
				?>
			
			</tbody>

			<tfoot>
				<tr>
					<td colspan="6">
						<div class="bulk-actions align-left">
							<?php
								if ($_SESSION['user']['Type'] == 1) echo"
								<input type=\"submit\" class=\"button\" value=\"删除\">";
							?>
						</div>

						<div class="pagination">
							<?php echo $this->paginationControl($this->paginator_publish,
								'Elastic',//页码样式 
								'admin/pagination_control.phtml'//页码模板
								);
							?>
						</div> <!-- End .pagination -->
						<div class="clear"></div>
					</td>
				</tr>
			</tfoot>

			</table>

		</div> <!-- End #publish -->

	</div> <!-- End .content-box-content -->

</div> <!-- End .content-box -->


<script type="text/javascript">

	$(document).ready(function(){
		$(
			<?php
				switch ($this->PublishType){
					case     "all": echo "\"#alltab\"";break;
					case    "wait": echo "\"#waittab\"";break;
					case  "reject": echo "\"#rejecttab\"";break;
					case "publish": echo "\"#publishtab\"";break;
					default       : echo "\"#alltab\"";break;
				}
			?>
		).click();
	});

	jQuery(document).ready(function($) {
		//超链接的rel属性是否具有facebox
		$('a[rel*=facebox]').facebox()
	});

	$(".delete").click(function() {
		return confirm("确定要删除这篇文章吗?");
	});

</script>