<?php
	$title = '统计';
	$type = $this->type;
	if ($type=='list') $title = '查看';
?>
<link rel="stylesheet" type="text/css" media="all" href="/css/admin/jquery-ui.css"/>
<script type="text/javascript" src="/scripts/admin/jquery.form.js"></script>
<script type="text/javascript" src="/scripts/admin/jquery-ui.min.js"></script>
<script type="text/javascript" src="/scripts/admin/jquery-ui-sliderAccess.js"></script>

<div id="messages">

	<h4>自定义<?=$title?></h4><hr>

	<form id="period" action="/admin/periodstatistics/type/post" method="post">
		&nbsp;起始日期：<input class="text-input" type="text" name="beginday" id="beginday" value="<?=$this->PrevWeekBeginDay?>" style="padding:3.5px;width:77px;" readonly>　结束日期：<input class="text-input" type="text" name="endday" id="endday" value="<?=$this->PrevWeekEndDay?>" style="padding:3.5px;width:77px;" readonly>&nbsp;　<input class="button" type="submit" value="查询"/><hr>
	</form>

	<div id="main-content" class="datalist" style="margin:0;padding:0;">
		<table>

			<thead>
				<tr>
				<th>学院名称</th>
				<th>已发表</th>
				<th>未发表</th>
				<th>总数</th>
				</tr>
			</thead>

			<tbody>
				<tr>
				<td>　　　　　　　　　　　</td>
				<td>　</td>
				<td>　</td>
				<td>　</td>
				</tr>
			</tbody>

		</table>

	</div>

</div> <!-- End #messages -->

<script type="text/javascript">
	jQuery(function($){
		$.datepicker.regional['zh-cn'] = {
			closeText: '关闭',
			prevText: '&#x3C;上月',
			nextText: '下月&#x3E;',
			currentText: '今天',
			monthNames: ['一月','二月','三月','四月','五月','六月',
			'七月','八月','九月','十月','十一月','十二月'],
			monthNamesShort: ['一月','二月','三月','四月','五月','六月',
			'七月','八月','九月','十月','十一月','十二月'],
			dayNames: ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],
			dayNamesShort: ['周日','周一','周二','周三','周四','周五','周六'],
			dayNamesMin: ['日','一','二','三','四','五','六'],
			weekHeader: '周',
			dateFormat: 'yy-mm-dd',
			firstDay: 1,
			isRTL: false,
			showWeek: true,
			showMonthAfterYear: true,
			yearSuffix: '年'};
		$.datepicker.setDefaults($.datepicker.regional['zh-cn']);
	});
	$("#beginday").datepicker();
	$("#endday").datepicker();

	// prepare the form when the DOM is ready 
	$(document).ready(function() {
		var options = { 
		target: '.datalist',
		// success: function(){alert('查询成功！');}
		}; 

		// bind form using 'ajaxForm' 
		$('#period').ajaxForm(options);
	});
</script>