<?php
	$UserType1Style = null;
	$UserType2Style = null;
	$UserType3Style = null;

	if ($this->isEdit) {
		$Type = 'edit';
		$Title = '修改用户信息';
		$User = $this->User;
		$UID = $User[0]['UID'];
		$UserName = " value=\"".$User[0]['UserName']."\"";
		$RealName = " value=\"".$User[0]['RealName']."\"";
		$DeptID = $User[0]['Department'];
		$UserType = $User[0]['Type'];
		switch ($UserType) {
			case '1': $UserType1Style = ' checked'; break;
			case '2': $UserType2Style = ' checked'; break;
			case '3': $UserType3Style = ' checked'; break;
			default : break;
		}
		$ButtonText = '确认修改';
	} else {
		$Type = 'add';
		$Title = '添加用户';
		$UserName = null;
		$RealName = null;
		$DeptID = -1;
		$ButtonText = '确认添加';
	}
?>
<div id="messages">

	<form action="/admin/usermanager/type/<?=$Type?>" method="post">

		<h4><?=$Title?></h4><hr>

		<fieldset>
			<p>　用户名： <input type="text" name="username" class="text-input" id="username" style="ime-mode: disabled; padding: 4px;"<?=$UserName?>></p>
			<p>真实姓名： <input type="text" name="realname" class="text-input" id="realname" style="padding: 4px;"<?=$RealName?>></p>
			<?php
			if ($this->isEdit) { ?>
			<p style="display: none;"><input type="text" name="id" value="<?=$UID?>"></p>
			<?php } else { ?>
			<p>　　密码： <input type="text" name="pwd" class="text-input" id="pwd" style="ime-mode: disabled; padding: 4px;" autocomplete="off"></p>
			<?php } ?>
			<p>所属学院： 
				<select name="deptid" class="deptid">
					<option value="-1">请选择学院</option>
					<?php
						$arrDept = $this->arrDept;
						$rowsDept = count($arrDept);
						for($i=0;$i<$rowsDept;$i++) {
							if ($DeptID==$arrDept[$i]['DeptID']) $DeptStyle=' selected';
							else $DeptStyle=null; ?>
							<option value="<?=$arrDept[$i]['DeptID']?>"<?=$DeptStyle?>><?=$arrDept[$i]['DeptName']?></option>
					<?php } ?>
				</select>
			</p>
			<p>用户权限： 
				<label class="power">
					<input type="radio" name="usertype" value="1" class="usertype"<?=$UserType1Style?>> 超级管理员
				</label>　
				<label class="power">
					<input type="radio" name="usertype" value="2" class="usertype"<?=$UserType2Style?>> 网站审核
				</label>　
				<label class="power">
					<input type="radio" name="usertype" value="3" class="usertype"<?=$UserType3Style?>> 网站编辑
				</label>
			</p>
			<hr>

			<p style="display: inline-block;position: relative;left: 40%;">
				<input class="button" type="submit" value="<?=$ButtonText?>"/>
			</p>

		</fieldset>

	</form>

</div> <!-- End #messages -->

<script type="text/javascript">
	$(".button").eq(2).click(function(){
		if (($("#username").val() == "") || ($("#realname").val() == "") || ($("#pwd").val() == "") || ($(".deptid").val() == -1) || ($(".usertype:checked").val() == null)) {
			if ($("#username").val() == "") {alert("亲，请填写用户名"); return false;}
			if ($("#realname").val() == "") {alert("亲，请填写真实姓名"); return false;}
			if ($("#pwd").val() == "") {alert("亲，请填写明文密码"); return false;}
			if ($(".deptid").val() == -1) {alert("亲，请选择学院"); return false;}
			if ($(".usertype:checked").val() == null) {alert("亲，请选择权限"); return false;}
		} else {
			return true;
		}
	});
</script>